/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package flamium;

import com.fazecast.jSerialComm.*;
import java.io.FileNotFoundException;

import java.util.logging.Level;
import java.util.logging.Logger;

//import gnu.io.*;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.Buffer;
import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.Timer;
import java.util.TimerTask;



/**
 *
 * @author koalium
 */
public class main extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form main
	 *
	 * @throws java.io.IOException
	 * @throws java.lang.InterruptedException
	 */
	public main() throws IOException, InterruptedException {
		this.fireticktime = firetimemillis/ticktimetaskmilis;
		this.bybu = ByteBuffer.allocate(125000);
		initComponents();
		jComboBoxComPortSelectionFileTab.removeAllItems();
		AvailablePorts = SerialPort.getCommPorts();
		//bybu.clear();
		for (SerialPort AvailablePort : AvailablePorts) {
			jComboBoxComPortSelectionFileTab.addItem(AvailablePort.getSystemPortName());
		}
		comboSerialComSelectionPortMainTab.repaint();
		timi();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jDialog1 = new javax.swing.JDialog();
                jSeparator1 = new javax.swing.JSeparator();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTextArea1 = new javax.swing.JTextArea();
                jPanel8 = new javax.swing.JPanel();
                jTabbedPaneFrame = new javax.swing.JTabbedPane();
                panelFire = new javax.swing.JPanel();
                jPanel1 = new javax.swing.JPanel();
                jButtonRefreshSerialListFileTab = new javax.swing.JButton();
                jComboBoxComPortSelectionFileTab = new javax.swing.JComboBox<>();
                jButtonConnectSerialFileTab = new javax.swing.JButton();
                jButtonFireInTheHole = new javax.swing.JButton();
                jButtonTestIrSensorsFileTab = new javax.swing.JButton();
                jButtonTestDataFileTab = new javax.swing.JButton();
                jPasswordFieldFireTabFile = new javax.swing.JPasswordField();
                jSeparator5 = new javax.swing.JSeparator();
                jLabelConnectionFileTab = new javax.swing.JLabel();
                jButtonCloseConnectionFileTab = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                jButtonTestPiezoTabFile = new javax.swing.JButton();
                jSeparator3 = new javax.swing.JSeparator();
                jSeparator4 = new javax.swing.JSeparator();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTextAreaMonitoringFileTab = new javax.swing.JTextArea();
                jButtonCalibreFileTab = new javax.swing.JButton();
                jLabelShowTerminal = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jPanelGas = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                jPanel4 = new javax.swing.JPanel();
                jPanel6 = new javax.swing.JPanel();
                jPanel7 = new javax.swing.JPanel();
                jPanellog = new javax.swing.JPanel();
                jPanelTabMainUp = new javax.swing.JPanel();
                jLabelPort = new javax.swing.JLabel();
                comboSerialComSelectionPortMainTab = new javax.swing.JComboBox<>();
                jLabelBaudRate = new javax.swing.JLabel();
                jButtonConnectMainTab = new javax.swing.JButton();
                jSeparator2 = new javax.swing.JSeparator();
                jLabelConnectionMainTab = new javax.swing.JLabel();
                jFormattedTextFieldBaudRateMainTab = new javax.swing.JFormattedTextField();
                jPanel5 = new javax.swing.JPanel();
                jLabelSerialMonitor = new javax.swing.JLabel();
                jTextField2 = new javax.swing.JTextField();
                jButtonSend = new javax.swing.JButton();
                jToggleButton1 = new javax.swing.JToggleButton();
                jSpinner3 = new javax.swing.JSpinner();
                jTextField5 = new javax.swing.JTextField();

                javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
                jDialog1.getContentPane().setLayout(jDialog1Layout);
                jDialog1Layout.setHorizontalGroup(
                        jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                );
                jDialog1Layout.setVerticalGroup(
                        jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
                );

                jTextArea1.setColumns(20);
                jTextArea1.setRows(5);
                jScrollPane1.setViewportView(jTextArea1);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("flamium");

                jTabbedPaneFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                jTabbedPaneFrame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                jTabbedPaneFrame.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
                jTabbedPaneFrame.setName("tabsFrame"); // NOI18N
                jTabbedPaneFrame.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                jTabbedPaneFrameMouseEntered(evt);
                        }
                });

                panelFire.setName("panelFire"); // NOI18N

                jButtonRefreshSerialListFileTab.setText("refresh");
                jButtonRefreshSerialListFileTab.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonRefreshSerialListFileTabActionPerformed(evt);
                        }
                });

                jComboBoxComPortSelectionFileTab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COM" }));
                jComboBoxComPortSelectionFileTab.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jComboBoxComPortSelectionFileTabActionPerformed(evt);
                        }
                });

                jButtonConnectSerialFileTab.setText("Connect");
                jButtonConnectSerialFileTab.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonConnectSerialFileTabActionPerformed(evt);
                        }
                });

                jButtonFireInTheHole.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
                jButtonFireInTheHole.setForeground(new java.awt.Color(0, 51, 51));
                jButtonFireInTheHole.setText("Fire");
                jButtonFireInTheHole.setEnabled(false);
                jButtonFireInTheHole.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonFireInTheHoleActionPerformed(evt);
                        }
                });

                jButtonTestIrSensorsFileTab.setText("Test IR");
                jButtonTestIrSensorsFileTab.setEnabled(false);
                jButtonTestIrSensorsFileTab.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonTestIrSensorsFileTabActionPerformed(evt);
                        }
                });

                jButtonTestDataFileTab.setText("test Data");
                jButtonTestDataFileTab.setEnabled(false);
                jButtonTestDataFileTab.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonTestDataFileTabActionPerformed(evt);
                        }
                });

                jPasswordFieldFireTabFile.setText("0");

                jLabelConnectionFileTab.setLabelFor(jButtonConnectSerialFileTab);
                jLabelConnectionFileTab.setText("push refresh");
                jLabelConnectionFileTab.setAlignmentX(0.5F);
                jLabelConnectionFileTab.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                jButtonCloseConnectionFileTab.setText("Close");
                jButtonCloseConnectionFileTab.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonCloseConnectionFileTabActionPerformed(evt);
                        }
                });

                jLabel1.setText("Monitoring:");
                jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                jButtonTestPiezoTabFile.setText("Test Piezo");
                jButtonTestPiezoTabFile.setEnabled(false);
                jButtonTestPiezoTabFile.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonTestPiezoTabFileActionPerformed(evt);
                        }
                });

                jTextAreaMonitoringFileTab.setColumns(20);
                jTextAreaMonitoringFileTab.setRows(5);
                jTextAreaMonitoringFileTab.setTabSize(4);
                jTextAreaMonitoringFileTab.addInputMethodListener(new java.awt.event.InputMethodListener() {
                        public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                        }
                        public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                                jTextAreaMonitoringFileTabInputMethodTextChanged(evt);
                        }
                });
                jScrollPane2.setViewportView(jTextAreaMonitoringFileTab);

                jButtonCalibreFileTab.setText("Calibre");
                jButtonCalibreFileTab.setEnabled(false);
                jButtonCalibreFileTab.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonCalibreFileTabActionPerformed(evt);
                        }
                });

                jLabelShowTerminal.setText("  ");
                jLabelShowTerminal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

                jLabel2.setText("Koalium LTD CopyRight 2024");
                jLabel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jSeparator5)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jButtonTestPiezoTabFile)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButtonTestDataFileTab)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jButtonTestIrSensorsFileTab)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jButtonCalibreFileTab)
                                                                .addGap(0, 352, Short.MAX_VALUE)))
                                                .addGap(17, 17, 17))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButtonFireInTheHole)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jPasswordFieldFireTabFile, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabelConnectionFileTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jSeparator3)
                                        .addComponent(jSeparator4)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButtonRefreshSerialListFileTab)
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboBoxComPortSelectionFileTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonConnectSerialFileTab)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonCloseConnectionFileTab)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabelShowTerminal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonRefreshSerialListFileTab)
                                        .addComponent(jComboBoxComPortSelectionFileTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonConnectSerialFileTab)
                                        .addComponent(jButtonCloseConnectionFileTab))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jButtonTestDataFileTab)
                                                .addComponent(jButtonTestIrSensorsFileTab)
                                                .addComponent(jButtonCalibreFileTab))
                                        .addComponent(jButtonTestPiezoTabFile))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonFireInTheHole)
                                        .addComponent(jPasswordFieldFireTabFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelConnectionFileTab))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelShowTerminal))
                                .addGap(21, 21, 21)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addContainerGap())
                );

                javax.swing.GroupLayout panelFireLayout = new javax.swing.GroupLayout(panelFire);
                panelFire.setLayout(panelFireLayout);
                panelFireLayout.setHorizontalGroup(
                        panelFireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFireLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                panelFireLayout.setVerticalGroup(
                        panelFireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFireLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                jTabbedPaneFrame.addTab("fire", panelFire);
                panelFire.getAccessibleContext().setAccessibleName("panelTabFile");

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 719, Short.MAX_VALUE)
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 173, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel6Layout.setVerticalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 129, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                jPanel7.setLayout(jPanel7Layout);
                jPanel7Layout.setHorizontalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel7Layout.setVerticalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 175, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jPanelGasLayout = new javax.swing.GroupLayout(jPanelGas);
                jPanelGas.setLayout(jPanelGasLayout);
                jPanelGasLayout.setHorizontalGroup(
                        jPanelGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                jPanelGasLayout.setVerticalGroup(
                        jPanelGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                jTabbedPaneFrame.addTab("gas", jPanelGas);

                jPanellog.setBorder(javax.swing.BorderFactory.createCompoundBorder());
                jPanellog.setName("tabmainpanel"); // NOI18N
                jPanellog.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                jPanellogFocusGained(evt);
                        }
                });
                jPanellog.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                jPanellogMouseEntered(evt);
                        }
                });

                jPanelTabMainUp.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                jPanelTabMainUpMouseEntered(evt);
                        }
                });

                jLabelPort.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabelPort.setText("PORT:");

                comboSerialComSelectionPortMainTab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COM0", "COM1", "COM2", "COM3" , "COM4", "COM5", "COM6", "COM7", "COM8", "COM9" , "COM10", "COM11", "COM12"  }));
                comboSerialComSelectionPortMainTab.setToolTipText("serial port");
                comboSerialComSelectionPortMainTab.setName("serialPortSelector"); // NOI18N
                comboSerialComSelectionPortMainTab.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                comboSerialComSelectionPortMainTabFocusGained(evt);
                        }
                });
                comboSerialComSelectionPortMainTab.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                comboSerialComSelectionPortMainTabActionPerformed(evt);
                        }
                });

                jLabelBaudRate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabelBaudRate.setText("BaudRate :");

                jButtonConnectMainTab.setText("connect");
                jButtonConnectMainTab.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonConnectMainTabActionPerformed(evt);
                        }
                });

                jLabelConnectionMainTab.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
                jLabelConnectionMainTab.setLabelFor(jButtonConnectMainTab);
                jLabelConnectionMainTab.setText("how");
                jLabelConnectionMainTab.setToolTipText("");
                jLabelConnectionMainTab.setAlignmentX(0.5F);

                jFormattedTextFieldBaudRateMainTab.setText("2000000");

                javax.swing.GroupLayout jPanelTabMainUpLayout = new javax.swing.GroupLayout(jPanelTabMainUp);
                jPanelTabMainUp.setLayout(jPanelTabMainUpLayout);
                jPanelTabMainUpLayout.setHorizontalGroup(
                        jPanelTabMainUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTabMainUpLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelPort)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboSerialComSelectionPortMainTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelBaudRate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldBaudRateMainTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonConnectMainTab)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelConnectionMainTab)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTabMainUpLayout.createSequentialGroup()
                                .addComponent(jSeparator2)
                                .addContainerGap())
                );
                jPanelTabMainUpLayout.setVerticalGroup(
                        jPanelTabMainUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTabMainUpLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelTabMainUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelPort)
                                        .addComponent(comboSerialComSelectionPortMainTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelBaudRate)
                                        .addComponent(jButtonConnectMainTab)
                                        .addComponent(jLabelConnectionMainTab)
                                        .addComponent(jFormattedTextFieldBaudRateMainTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                jPanel5.setAutoscrolls(true);
                jPanel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
                jPanel5.setName("textFieldSerialRecived"); // NOI18N

                jLabelSerialMonitor.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
                jLabelSerialMonitor.setText("serial monitoring:");

                jTextField2.setText(" ");

                jButtonSend.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jButtonSend.setText("Send");

                jToggleButton1.setText("always");

                jSpinner3.setModel(new javax.swing.SpinnerListModel(new String[] {"nothing", "newLine", "Return Car", "NL RC", "costum char"}));

                jTextField5.setText("EOL");
                jTextField5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField5ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabelSerialMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonSend, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jTextField2))
                                .addContainerGap())
                );
                jPanel5Layout.setVerticalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                                        .addComponent(jSpinner3)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelSerialMonitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(374, 374, 374))
                );

                javax.swing.GroupLayout jPanellogLayout = new javax.swing.GroupLayout(jPanellog);
                jPanellog.setLayout(jPanellogLayout);
                jPanellogLayout.setHorizontalGroup(
                        jPanellogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanellogLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanellogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanelTabMainUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                jPanellogLayout.setVerticalGroup(
                        jPanellogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanellogLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelTabMainUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                jPanel5.getAccessibleContext().setAccessibleName("");

                jTabbedPaneFrame.addTab("log", jPanellog);
                jPanellog.getAccessibleContext().setAccessibleName("panelMain");

                javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
                jPanel8.setLayout(jPanel8Layout);
                jPanel8Layout.setHorizontalGroup(
                        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jTabbedPaneFrame)
                                .addContainerGap())
                );
                jPanel8Layout.setVerticalGroup(
                        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPaneFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jTabbedPaneFrameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneFrameMouseEntered
                /*// TODO add your handling code here:
                // TODO add your handling code here:
                // TODO add your handling code here:
                // TODO add your handling code here:
                // TODO add your handling code here:
                comboSerialComSelectionPortMainTab.removeAllItems();
                AvailablePorts = SerialPort.getCommPorts();
                for(int i = 0; i < AvailablePorts.length; i++)
                comboSerialComSelectionPortMainTab.addItem(AvailablePorts[i].getSystemPortName());
                comboSerialComSelectionPortMainTab.repaint();
                jLabelConnectionMainTab.setText("Port Refreshed");*/
        }//GEN-LAST:event_jTabbedPaneFrameMouseEntered

        private void jPanellogMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanellogMouseEntered

        }//GEN-LAST:event_jPanellogMouseEntered

        private void jPanellogFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanellogFocusGained

        }//GEN-LAST:event_jPanellogFocusGained

        private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTextField5ActionPerformed

        private void jPanelTabMainUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTabMainUpMouseEntered

        }//GEN-LAST:event_jPanelTabMainUpMouseEntered

        private void jButtonConnectMainTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectMainTabActionPerformed
                // TODO add your handling code here:

        }//GEN-LAST:event_jButtonConnectMainTabActionPerformed

        private void comboSerialComSelectionPortMainTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSerialComSelectionPortMainTabActionPerformed
                // TODO add your handling code here:
                jLabelConnectionMainTab.setText("Connecting...");

                if (sp == AvailablePorts[comboSerialComSelectionPortMainTab.getSelectedIndex()] && sp.isOpen()) {
                        jLabelConnectionMainTab.setText(sp.toString() + "...Connected");
                        return;
                }
                sp = AvailablePorts[comboSerialComSelectionPortMainTab.getSelectedIndex()];
                sp.setComPortParameters((int) BaudRate, DataBits, StopBits, Parity); // default connection settings for Arduino
                sp.setComPortTimeouts(SerialPort.TIMEOUT_READ_SEMI_BLOCKING, 7000, 1000); // block until bytes can be written
                if (sp.isOpen()) {
                        jButtonSend.setEnabled(true);
                }
                if (sp.openPort()) {
                        jLabelConnectionMainTab.setText("Port is open :)");
                        jButtonSend.setEnabled(true);
                } else {
                        jLabelConnectionMainTab.setText("Failed to open port :(");

                }
        }//GEN-LAST:event_comboSerialComSelectionPortMainTabActionPerformed

        private void comboSerialComSelectionPortMainTabFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboSerialComSelectionPortMainTabFocusGained
                // TODO add your handling code here:
        }//GEN-LAST:event_comboSerialComSelectionPortMainTabFocusGained

        private void jButtonCalibreFileTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalibreFileTabActionPerformed

        }//GEN-LAST:event_jButtonCalibreFileTabActionPerformed

        private void jButtonTestPiezoTabFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestPiezoTabFileActionPerformed
                // TODO add your handling code here:

                jLabelConnectionFileTab.setText("reading piezo value...");
		piezotocheck = true;
               
                
        }//GEN-LAST:event_jButtonTestPiezoTabFileActionPerformed

        private void jButtonCloseConnectionFileTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseConnectionFileTabActionPerformed
                // TODO add your handling code here:
                if (sp.isOpen()) {
                        sp.closePort();
                        jLabelConnectionFileTab.setText(sp.toString() + "  ...CLOSE IT...");
                } else {
                        jLabelConnectionFileTab.setText(sp.toString() + "  ...not opened yet..");
                }
        }//GEN-LAST:event_jButtonCloseConnectionFileTabActionPerformed

        private void jButtonTestDataFileTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestDataFileTabActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonTestDataFileTabActionPerformed

        private void jButtonTestIrSensorsFileTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestIrSensorsFileTabActionPerformed
                // TODO add your handling code here:

        }//GEN-LAST:event_jButtonTestIrSensorsFileTabActionPerformed

        private void jButtonFireInTheHoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFireInTheHoleActionPerformed
                if (String.valueOf(jPasswordFieldFireTabFile.getPassword()) == null ? default_fire_password != null : !String.valueOf(jPasswordFieldFireTabFile.getPassword()).equals(default_fire_password)) {
                        jLabelConnectionFileTab.setText("password incorrect!!!...");
                        return;
                }
                jLabelConnectionFileTab.setText("fire in the hole..!!");
                try {
                        //
                        Thread.sleep(00);
                } catch (InterruptedException e) {
                }
                //fireIntheHole();
		currmodefire = true;
        }//GEN-LAST:event_jButtonFireInTheHoleActionPerformed

        private void jButtonConnectSerialFileTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectSerialFileTabActionPerformed
                // TODO add your handling code here:
                jLabelConnectionFileTab.setText("Connecting...");

                if (sp == AvailablePorts[jComboBoxComPortSelectionFileTab.getSelectedIndex()] && sp.isOpen()) {
                        jLabelConnectionFileTab.setText(sp.toString() + "...Connected");
                        return;
                }
                sp = AvailablePorts[jComboBoxComPortSelectionFileTab.getSelectedIndex()];
                sp.openPort(1000);
                sp.setComPortParameters((int) BaudRate, DataBits, StopBits, Parity); // default connection settings for Arduino
                sp.setComPortTimeouts(SerialPort.TIMEOUT_READ_SEMI_BLOCKING, 1, 1); // block until bytes can be written

                //tm.setDelay(500);
                if (sp.isOpen()) {
                        jButtonFireInTheHole.setEnabled(true);
                        jButtonTestDataFileTab.setEnabled(true);
                        jButtonTestIrSensorsFileTab.setEnabled(true);
                        jButtonTestPiezoTabFile.setEnabled(true);
                        jButtonCalibreFileTab.setEnabled(true);
                        jLabelConnectionFileTab.setText("Port is open :)");
                }
                else {
                        jLabelConnectionFileTab.setText("Failed to open port :(");
                }
               
        }//GEN-LAST:event_jButtonConnectSerialFileTabActionPerformed

        private void jComboBoxComPortSelectionFileTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxComPortSelectionFileTabActionPerformed
                // TODO add your handling code here:

        }//GEN-LAST:event_jComboBoxComPortSelectionFileTabActionPerformed

        private void jButtonRefreshSerialListFileTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshSerialListFileTabActionPerformed
                // TODO add your handling code here:
                jComboBoxComPortSelectionFileTab.removeAllItems();
                AvailablePorts = SerialPort.getCommPorts();
                for (SerialPort AvailablePort : AvailablePorts) {
                        jComboBoxComPortSelectionFileTab.addItem(AvailablePort.getSystemPortName());
                }
                comboSerialComSelectionPortMainTab.repaint();
                jLabelConnectionFileTab.setText("Port Refreshed");
        }//GEN-LAST:event_jButtonRefreshSerialListFileTabActionPerformed

        private void jTextAreaMonitoringFileTabInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextAreaMonitoringFileTabInputMethodTextChanged
                // TODO add your handling code here:
        }//GEN-LAST:event_jTextAreaMonitoringFileTabInputMethodTextChanged

	//

	public boolean serialSend(String ss) {
		//return value for whether opening the streams is successful or not
		if (sp.isOpen()) {
			sp.writeBytes(ss.getBytes(), ss.getBytes().length);
			return true;
		}

		return false;
	}





	//
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> {
			try {
				new main().setVisible(true);
			} catch (IOException | InterruptedException ex) {
				Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
			}
		});
	}
	
		//
	private synchronized TimerTask tt(){
		
		tt =  new TimerTask() {
			@Override
			public void run() {
				monitoring();
				
				try {
					timeFiring();
					todoFunc();
				} catch (IOException ex) {
					Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
				}
			
			}
		};
		return tt;
	}

	//
	private  void timi(){
		timer = new Timer();
		timer.scheduleAtFixedRate(tt(), 0, 1);
	}
	
	
	private void recheckFireRunSlice(){
		if(fireRunning==false){
			return;
		}
		
		if (sp.bytesAvailable() > 0) {
			byte[] nb = new byte[sp.bytesAvailable() ];
			sp.readBytes(nb, nb.length-1) ;
					
			bybu.put(nb);
		}

					
				
	}
	
	private void timeFiring() throws IOException{
		
		if(pervmodefire ){
			if(currmodefire){
				monitoring = false;
				recheckFireRunSlice();
				if(firetickcounter++>10*fireticktime){
					
					currmodefire=false;
					saveFireResultIn();
					showFireResultIn();
				}
				
			}else{
				currmodefire=false;
				fireRunning = false;
				//saveFireResultIn();
				//showFireResultIn();
			}
			
		}else{
			if(currmodefire){
				fireRunning = true;
				startFireIn();
				
			}else{
				
			}
		}
		
		pervmodefire = currmodefire;
	}
	
	private void startFireIn(){
		byte[] bufferb = {'f', 'i', 'r', 'e', '8', '\n', '\n',0};
		int bufferbindexreader = 0;
		
		
		sp.writeBytes(bufferb, bufferb.length-1);
	}
	
	//
	private void showFireResultIn()
	{
		
	}
	//
	private void saveFireResultIn() throws FileNotFoundException, IOException
	{
		
		
		
		
			OutputStream Stream = new FileOutputStream("log_.bin");
			
			if (bybu.hasArray()) {
				Stream.write(bybu.array());
			}
			Stream.close();
		
		
		
		Stream = new FileOutputStream("log_.txt") ;
		for(byte b :bybu.array()){
			int i;
				i = b;
				if(i<0){
					i+=256;
				}
			String ss=Integer.toString(b)+"\n";
			Stream.write(ss.getBytes());
		}	
		
		Stream.close();	
			
		
	}
	
	void monitoring(){
		if(monitoring){
			if(sp!=null && sp.bytesAvailable()>0){
				byte[] b = new byte[sp.bytesAvailable()];
				sp.readBytes(b, b.length-1);
				String ss ="";
				for(byte bb:b){
					ss+=(char)bb;
				}
				jTextAreaMonitoringFileTab.setText(jTextAreaMonitoringFileTab.getText()+ss);
			}
			
		}
	}
	
	void todoFunc() throws FileNotFoundException, IOException{
		if(piezochecked){
			piezotocheck = false;
			piezochecking = false;
			piezochecked = false;
			if(piezoreckecking){
				piezotocheck = true;
			}
			
		}else
		if(piezochecking){
			byte[] b = new byte[sp.bytesAvailable()];
			sp.readBytes(b, b.length);
			jLabelShowTerminal.setText(Arrays.toString(b) + " " );
			OutputStream Stream = new FileOutputStream("calibre.bin");
			int calvalue = b[0]+b[1];
			Stream.write(calvalue);
			Stream.close();
			piezochecked=true;
			piezotocheck = false;
		}else
		if(piezotocheck){
			serialSend(_str_piezotest_);
			piezochecking = true;
		}
	}
	
	boolean piezotocheck = false;
	boolean piezochecking = false;
	boolean piezochecked = false;
	boolean piezoreckecking = false;
	boolean monitoring = true;
	boolean pervmodefire = false;
	boolean currmodefire = false;
	
	int firetickcounter = 0;
	int fireticktime;
	final int ticktimetaskmilis = 1;
	final int firetimemillis = 1000;
	ByteBuffer bybu ;
	boolean fireRunning = false;
	static public long BaudRate = 2000000;
	static public int DataBits = 8;
	static public int StopBits = SerialPort.ONE_STOP_BIT;
	static public int Parity = SerialPort.NO_PARITY;
	//static public String comportstr = "COM";
	//static public String serialPortNameList[] = {"COM0","COM1"};
	static public SerialPort sp;
	String _str_calibre = "clbr\n";
	String _str_irtest_ ="tstir\n";
	String _str_piezotest_ ="tstpzo";
	String gstr = "";
	Buffer gbuffer;
	Timer timer;
	TimerTask tt;
	final byte[] startbytes = {'b','i','h','b','i','h'};
	final byte[] stopbytes = {'m','i','g','m','i','g'};
	final byte[] finbytes = {'f','l','a','m','i','u','m'};
	final String startstring = "bihbih";
	final String stopstring = "migmig";
	final String finstring = "flamiumLtd";
	static public SerialPort[] AvailablePorts;
	String default_fire_password = "8";
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JComboBox<String> comboSerialComSelectionPortMainTab;
        private javax.swing.JButton jButtonCalibreFileTab;
        private javax.swing.JButton jButtonCloseConnectionFileTab;
        private javax.swing.JButton jButtonConnectMainTab;
        private javax.swing.JButton jButtonConnectSerialFileTab;
        private javax.swing.JButton jButtonFireInTheHole;
        private javax.swing.JButton jButtonRefreshSerialListFileTab;
        private javax.swing.JButton jButtonSend;
        private javax.swing.JButton jButtonTestDataFileTab;
        private javax.swing.JButton jButtonTestIrSensorsFileTab;
        private javax.swing.JButton jButtonTestPiezoTabFile;
        private javax.swing.JComboBox<String> jComboBoxComPortSelectionFileTab;
        private javax.swing.JDialog jDialog1;
        private javax.swing.JFormattedTextField jFormattedTextFieldBaudRateMainTab;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabelBaudRate;
        private javax.swing.JLabel jLabelConnectionFileTab;
        private javax.swing.JLabel jLabelConnectionMainTab;
        private javax.swing.JLabel jLabelPort;
        private javax.swing.JLabel jLabelSerialMonitor;
        private javax.swing.JLabel jLabelShowTerminal;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JPanel jPanel7;
        private javax.swing.JPanel jPanel8;
        private javax.swing.JPanel jPanelGas;
        private javax.swing.JPanel jPanelTabMainUp;
        private javax.swing.JPanel jPanellog;
        private javax.swing.JPasswordField jPasswordFieldFireTabFile;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JSeparator jSeparator2;
        private javax.swing.JSeparator jSeparator3;
        private javax.swing.JSeparator jSeparator4;
        private javax.swing.JSeparator jSeparator5;
        private javax.swing.JSpinner jSpinner3;
        private javax.swing.JTabbedPane jTabbedPaneFrame;
        private javax.swing.JTextArea jTextArea1;
        private javax.swing.JTextArea jTextAreaMonitoringFileTab;
        private javax.swing.JTextField jTextField2;
        private javax.swing.JTextField jTextField5;
        private javax.swing.JToggleButton jToggleButton1;
        private javax.swing.JPanel panelFire;
        // End of variables declaration//GEN-END:variables
}
