/*
 * The MIT License
 *
 * Copyright 2025 koalium.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package departed;

import java.awt.Color;

/**
 *
 * @author koalium
 */
public class FormMixture extends javax.swing.JFrame {

	/**
	 * Creates new form FormMixture
	 */
	public FormMixture() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanelRoot = new javax.swing.JPanel();
                jPanelMonitor = new javax.swing.JPanel();
                jPanelMonitorPressure = new javax.swing.JPanel();
                jLabelMonitorPressure = new javax.swing.JLabel();
                jPanelMonitorTemp = new javax.swing.JPanel();
                jLabelMonitorTemp = new javax.swing.JLabel();
                jPanelMonitorFlam = new javax.swing.JPanel();
                jLabelMonitorFlammable = new javax.swing.JLabel();
                jPanel5 = new javax.swing.JPanel();
                jPanelMonitorAir = new javax.swing.JPanel();
                jPanelAirTem = new javax.swing.JPanel();
                jLabelAAirTemp = new javax.swing.JLabel();
                jPanelAirPres = new javax.swing.JPanel();
                jLabelAirPress = new javax.swing.JLabel();
                jPanelMonitorOxy = new javax.swing.JPanel();
                jPanelOxyPres = new javax.swing.JPanel();
                jLabelOxyPress = new javax.swing.JLabel();
                jPanelOxyTem = new javax.swing.JPanel();
                jLabelAOxyTemp = new javax.swing.JLabel();
                jPanelMonitorGas = new javax.swing.JPanel();
                jPanelGasTem = new javax.swing.JPanel();
                jLabelAFlamTemp = new javax.swing.JLabel();
                jPanelGasPres = new javax.swing.JPanel();
                jLabelFlamPress = new javax.swing.JLabel();
                jPanelMix = new javax.swing.JPanel();
                jPanelMixGas = new javax.swing.JPanel();
                jFormattedTextFieldFlam = new javax.swing.JFormattedTextField();
                jButtonMix = new javax.swing.JButton();
                jPanelMixAir = new javax.swing.JPanel();
                jFormattedTextFieldAir = new javax.swing.JFormattedTextField();
                jPanelMixOxy = new javax.swing.JPanel();
                jFormattedTextFieldOxy = new javax.swing.JFormattedTextField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Mixture");
                setLocation(new java.awt.Point(15, 233));
                setName("frameMixture"); // NOI18N

                jPanelRoot.setBackground(new java.awt.Color(153, 153, 255));
                jPanelRoot.setForeground(new java.awt.Color(204, 204, 255));

                jPanelMonitor.setBackground(new java.awt.Color(153, 153, 255));
                jPanelMonitor.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Monitoring:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.gray))); // NOI18N
                jPanelMonitor.setForeground(new java.awt.Color(153, 153, 255));

                jPanelMonitorPressure.setBackground(new java.awt.Color(153, 153, 255));
                jPanelMonitorPressure.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pressue", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial", 3, 12), new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 102, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(0, 51, 153), new java.awt.Color(0, 0, 255)))); // NOI18N
                jPanelMonitorPressure.setForeground(new java.awt.Color(153, 153, 255));
                jPanelMonitorPressure.setMinimumSize(new java.awt.Dimension(120, 0));

                jLabelMonitorPressure.setBackground(new java.awt.Color(153, 153, 255));
                jLabelMonitorPressure.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
                jLabelMonitorPressure.setForeground(new java.awt.Color(51, 0, 0));
                jLabelMonitorPressure.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelMonitorPressure.setText("101.55");
                jLabelMonitorPressure.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.pink, java.awt.Color.orange));

                javax.swing.GroupLayout jPanelMonitorPressureLayout = new javax.swing.GroupLayout(jPanelMonitorPressure);
                jPanelMonitorPressure.setLayout(jPanelMonitorPressureLayout);
                jPanelMonitorPressureLayout.setHorizontalGroup(
                        jPanelMonitorPressureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMonitorPressureLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelMonitorPressure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanelMonitorPressureLayout.setVerticalGroup(
                        jPanelMonitorPressureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMonitorPressureLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelMonitorPressure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );

                jPanelMonitorTemp.setBackground(new java.awt.Color(153, 153, 255));
                jPanelMonitorTemp.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Temprature", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial", 3, 12), new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 102, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(0, 51, 153), new java.awt.Color(0, 0, 255)))); // NOI18N
                jPanelMonitorTemp.setForeground(new java.awt.Color(153, 153, 255));

                jLabelMonitorTemp.setBackground(new java.awt.Color(153, 153, 255));
                jLabelMonitorTemp.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
                jLabelMonitorTemp.setForeground(new java.awt.Color(51, 0, 0));
                jLabelMonitorTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelMonitorTemp.setText("101.55");
                jLabelMonitorTemp.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.pink, java.awt.Color.orange));

                javax.swing.GroupLayout jPanelMonitorTempLayout = new javax.swing.GroupLayout(jPanelMonitorTemp);
                jPanelMonitorTemp.setLayout(jPanelMonitorTempLayout);
                jPanelMonitorTempLayout.setHorizontalGroup(
                        jPanelMonitorTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMonitorTempLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelMonitorTemp, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanelMonitorTempLayout.setVerticalGroup(
                        jPanelMonitorTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMonitorTempLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelMonitorTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );

                jPanelMonitorFlam.setBackground(new java.awt.Color(153, 153, 255));
                jPanelMonitorFlam.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Flammable", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial", 3, 12), new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 102, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(0, 51, 153), new java.awt.Color(0, 0, 255)))); // NOI18N
                jPanelMonitorFlam.setForeground(new java.awt.Color(153, 153, 255));
                jPanelMonitorFlam.setMinimumSize(new java.awt.Dimension(120, 0));
                jPanelMonitorFlam.setPreferredSize(new java.awt.Dimension(120, 73));

                jLabelMonitorFlammable.setBackground(new java.awt.Color(153, 153, 255));
                jLabelMonitorFlammable.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
                jLabelMonitorFlammable.setForeground(new java.awt.Color(51, 0, 0));
                jLabelMonitorFlammable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelMonitorFlammable.setText("101.55");
                jLabelMonitorFlammable.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.pink, java.awt.Color.orange));

                javax.swing.GroupLayout jPanelMonitorFlamLayout = new javax.swing.GroupLayout(jPanelMonitorFlam);
                jPanelMonitorFlam.setLayout(jPanelMonitorFlamLayout);
                jPanelMonitorFlamLayout.setHorizontalGroup(
                        jPanelMonitorFlamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMonitorFlamLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelMonitorFlammable, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanelMonitorFlamLayout.setVerticalGroup(
                        jPanelMonitorFlamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMonitorFlamLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelMonitorFlammable, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                .addContainerGap())
                );

                javax.swing.GroupLayout jPanelMonitorLayout = new javax.swing.GroupLayout(jPanelMonitor);
                jPanelMonitor.setLayout(jPanelMonitorLayout);
                jPanelMonitorLayout.setHorizontalGroup(
                        jPanelMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMonitorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelMonitorPressure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelMonitorTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelMonitorFlam, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                jPanelMonitorLayout.setVerticalGroup(
                        jPanelMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMonitorLayout.createSequentialGroup()
                                .addContainerGap(9, Short.MAX_VALUE)
                                .addGroup(jPanelMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanelMonitorTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanelMonitorPressure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanelMonitorFlam, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
                );

                jPanel5.setBackground(new java.awt.Color(153, 153, 255));
                jPanel5.setPreferredSize(new java.awt.Dimension(200, 200));

                jPanelMonitorAir.setBackground(new java.awt.Color(153, 153, 255));
                jPanelMonitorAir.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Air", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial", 3, 12), new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 102, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(0, 51, 153), new java.awt.Color(0, 0, 255)))); // NOI18N
                jPanelMonitorAir.setForeground(new java.awt.Color(153, 153, 255));

                jPanelAirTem.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createTitledBorder(null, "Temprature", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0)))); // NOI18N
                jPanelAirTem.setForeground(java.awt.SystemColor.controlShadow);

                jLabelAAirTemp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabelAAirTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelAAirTemp.setText("28");
                jLabelAAirTemp.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

                javax.swing.GroupLayout jPanelAirTemLayout = new javax.swing.GroupLayout(jPanelAirTem);
                jPanelAirTem.setLayout(jPanelAirTemLayout);
                jPanelAirTemLayout.setHorizontalGroup(
                        jPanelAirTemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAirTemLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelAAirTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanelAirTemLayout.setVerticalGroup(
                        jPanelAirTemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelAirTemLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelAAirTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                jPanelAirPres.setBackground(java.awt.SystemColor.inactiveCaption);
                jPanelAirPres.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createTitledBorder(null, "Pressure", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0)))); // NOI18N

                jLabelAirPress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabelAirPress.setForeground(new java.awt.Color(0, 0, 0));
                jLabelAirPress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelAirPress.setText("6.33");
                jLabelAirPress.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                javax.swing.GroupLayout jPanelAirPresLayout = new javax.swing.GroupLayout(jPanelAirPres);
                jPanelAirPres.setLayout(jPanelAirPresLayout);
                jPanelAirPresLayout.setHorizontalGroup(
                        jPanelAirPresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelAirPresLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelAirPress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanelAirPresLayout.setVerticalGroup(
                        jPanelAirPresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAirPresLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelAirPress)
                                .addContainerGap())
                );

                javax.swing.GroupLayout jPanelMonitorAirLayout = new javax.swing.GroupLayout(jPanelMonitorAir);
                jPanelMonitorAir.setLayout(jPanelMonitorAirLayout);
                jPanelMonitorAirLayout.setHorizontalGroup(
                        jPanelMonitorAirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMonitorAirLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelMonitorAirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanelAirPres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanelAirTem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                jPanelMonitorAirLayout.setVerticalGroup(
                        jPanelMonitorAirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMonitorAirLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelAirPres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelAirTem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                jPanelMonitorOxy.setBackground(new java.awt.Color(153, 153, 255));
                jPanelMonitorOxy.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Oxygen", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial", 3, 12), new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 102, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(0, 51, 153), new java.awt.Color(0, 0, 255)))); // NOI18N
                jPanelMonitorOxy.setForeground(new java.awt.Color(153, 153, 255));

                jPanelOxyPres.setBackground(java.awt.SystemColor.inactiveCaption);
                jPanelOxyPres.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createTitledBorder(null, "Pressure", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0)))); // NOI18N

                jLabelOxyPress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabelOxyPress.setForeground(new java.awt.Color(0, 0, 0));
                jLabelOxyPress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelOxyPress.setText("6.33");
                jLabelOxyPress.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                javax.swing.GroupLayout jPanelOxyPresLayout = new javax.swing.GroupLayout(jPanelOxyPres);
                jPanelOxyPres.setLayout(jPanelOxyPresLayout);
                jPanelOxyPresLayout.setHorizontalGroup(
                        jPanelOxyPresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelOxyPresLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelOxyPress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanelOxyPresLayout.setVerticalGroup(
                        jPanelOxyPresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelOxyPresLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelOxyPress)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                jPanelOxyTem.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createTitledBorder(null, "Temprature", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0)))); // NOI18N
                jPanelOxyTem.setForeground(java.awt.SystemColor.controlShadow);

                jLabelAOxyTemp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabelAOxyTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelAOxyTemp.setText("28");
                jLabelAOxyTemp.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

                javax.swing.GroupLayout jPanelOxyTemLayout = new javax.swing.GroupLayout(jPanelOxyTem);
                jPanelOxyTem.setLayout(jPanelOxyTemLayout);
                jPanelOxyTemLayout.setHorizontalGroup(
                        jPanelOxyTemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOxyTemLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelAOxyTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanelOxyTemLayout.setVerticalGroup(
                        jPanelOxyTemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelOxyTemLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelAOxyTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                javax.swing.GroupLayout jPanelMonitorOxyLayout = new javax.swing.GroupLayout(jPanelMonitorOxy);
                jPanelMonitorOxy.setLayout(jPanelMonitorOxyLayout);
                jPanelMonitorOxyLayout.setHorizontalGroup(
                        jPanelMonitorOxyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMonitorOxyLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelMonitorOxyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanelOxyPres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanelOxyTem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                jPanelMonitorOxyLayout.setVerticalGroup(
                        jPanelMonitorOxyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMonitorOxyLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelOxyPres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelOxyTem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                jPanelMonitorGas.setBackground(new java.awt.Color(153, 153, 255));
                jPanelMonitorGas.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Flammable", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial", 3, 12), new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 102, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(0, 51, 153), new java.awt.Color(0, 0, 255)))); // NOI18N
                jPanelMonitorGas.setForeground(new java.awt.Color(153, 153, 255));

                jPanelGasTem.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createTitledBorder(null, "Temprature", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0)))); // NOI18N
                jPanelGasTem.setForeground(java.awt.SystemColor.controlShadow);

                jLabelAFlamTemp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabelAFlamTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelAFlamTemp.setText("28");
                jLabelAFlamTemp.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

                javax.swing.GroupLayout jPanelGasTemLayout = new javax.swing.GroupLayout(jPanelGasTem);
                jPanelGasTem.setLayout(jPanelGasTemLayout);
                jPanelGasTemLayout.setHorizontalGroup(
                        jPanelGasTemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGasTemLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelAFlamTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanelGasTemLayout.setVerticalGroup(
                        jPanelGasTemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelGasTemLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelAFlamTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                jPanelGasPres.setBackground(java.awt.SystemColor.inactiveCaption);
                jPanelGasPres.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createTitledBorder(null, "Pressure", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0)))); // NOI18N

                jLabelFlamPress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabelFlamPress.setForeground(new java.awt.Color(0, 0, 0));
                jLabelFlamPress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelFlamPress.setText("6.33");
                jLabelFlamPress.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                javax.swing.GroupLayout jPanelGasPresLayout = new javax.swing.GroupLayout(jPanelGasPres);
                jPanelGasPres.setLayout(jPanelGasPresLayout);
                jPanelGasPresLayout.setHorizontalGroup(
                        jPanelGasPresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelGasPresLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelFlamPress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanelGasPresLayout.setVerticalGroup(
                        jPanelGasPresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelGasPresLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelFlamPress)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jPanelMonitorGasLayout = new javax.swing.GroupLayout(jPanelMonitorGas);
                jPanelMonitorGas.setLayout(jPanelMonitorGasLayout);
                jPanelMonitorGasLayout.setHorizontalGroup(
                        jPanelMonitorGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMonitorGasLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelMonitorGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanelGasPres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanelGasTem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                jPanelMonitorGasLayout.setVerticalGroup(
                        jPanelMonitorGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMonitorGasLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelGasPres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelGasTem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanelMonitorAir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelMonitorOxy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelMonitorGas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel5Layout.setVerticalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPanelMonitorOxy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanelMonitorAir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanelMonitorGas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(9, Short.MAX_VALUE))
                );

                jPanelMix.setBackground(new java.awt.Color(153, 153, 255));
                jPanelMix.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mixer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.gray))); // NOI18N
                jPanelMix.setForeground(new java.awt.Color(153, 153, 255));

                jPanelMixGas.setBackground(new java.awt.Color(153, 153, 255));
                jPanelMixGas.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Propane", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial", 3, 12), new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 102, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(0, 51, 153), new java.awt.Color(0, 0, 255)))); // NOI18N
                jPanelMixGas.setForeground(new java.awt.Color(153, 153, 255));

                jFormattedTextFieldFlam.setColumns(5);
                jFormattedTextFieldFlam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jFormattedTextFieldFlam.setText("0.00");
                jFormattedTextFieldFlam.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                jFormattedTextFieldFlam.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jFormattedTextFieldFlamActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanelMixGasLayout = new javax.swing.GroupLayout(jPanelMixGas);
                jPanelMixGas.setLayout(jPanelMixGasLayout);
                jPanelMixGasLayout.setHorizontalGroup(
                        jPanelMixGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMixGasLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jFormattedTextFieldFlam)
                                .addContainerGap())
                );
                jPanelMixGasLayout.setVerticalGroup(
                        jPanelMixGasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMixGasLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jFormattedTextFieldFlam)
                                .addContainerGap())
                );

                jButtonMix.setBackground(java.awt.Color.cyan);
                jButtonMix.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jButtonMix.setForeground(new java.awt.Color(0, 0, 0));
                jButtonMix.setText("Add");
                jButtonMix.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                jButtonMixMousePressed(evt);
                        }
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jButtonMixMouseReleased(evt);
                        }
                });
                jButtonMix.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonMixActionPerformed(evt);
                        }
                });

                jPanelMixAir.setBackground(new java.awt.Color(153, 153, 255));
                jPanelMixAir.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Air", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial", 3, 12), new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 102, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(0, 51, 153), new java.awt.Color(0, 0, 255)))); // NOI18N
                jPanelMixAir.setForeground(new java.awt.Color(153, 153, 255));

                jFormattedTextFieldAir.setColumns(5);
                jFormattedTextFieldAir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
                jFormattedTextFieldAir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jFormattedTextFieldAir.setText("0.00");
                jFormattedTextFieldAir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                jFormattedTextFieldAir.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jFormattedTextFieldAirActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanelMixAirLayout = new javax.swing.GroupLayout(jPanelMixAir);
                jPanelMixAir.setLayout(jPanelMixAirLayout);
                jPanelMixAirLayout.setHorizontalGroup(
                        jPanelMixAirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMixAirLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jFormattedTextFieldAir)
                                .addContainerGap())
                );
                jPanelMixAirLayout.setVerticalGroup(
                        jPanelMixAirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMixAirLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jFormattedTextFieldAir)
                                .addContainerGap())
                );

                jPanelMixOxy.setBackground(new java.awt.Color(153, 153, 255));
                jPanelMixOxy.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Oxygen", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial", 3, 12), new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 102, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(0, 51, 153), new java.awt.Color(0, 0, 255)))); // NOI18N
                jPanelMixOxy.setForeground(new java.awt.Color(153, 153, 255));

                jFormattedTextFieldOxy.setColumns(5);
                jFormattedTextFieldOxy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jFormattedTextFieldOxy.setText("0.00");
                jFormattedTextFieldOxy.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                jFormattedTextFieldOxy.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jFormattedTextFieldOxyActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanelMixOxyLayout = new javax.swing.GroupLayout(jPanelMixOxy);
                jPanelMixOxy.setLayout(jPanelMixOxyLayout);
                jPanelMixOxyLayout.setHorizontalGroup(
                        jPanelMixOxyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMixOxyLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jFormattedTextFieldOxy)
                                .addContainerGap())
                );
                jPanelMixOxyLayout.setVerticalGroup(
                        jPanelMixOxyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMixOxyLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jFormattedTextFieldOxy)
                                .addContainerGap())
                );

                javax.swing.GroupLayout jPanelMixLayout = new javax.swing.GroupLayout(jPanelMix);
                jPanelMix.setLayout(jPanelMixLayout);
                jPanelMixLayout.setHorizontalGroup(
                        jPanelMixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMixLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelMixAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelMixOxy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelMixGas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonMix, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                jPanelMixLayout.setVerticalGroup(
                        jPanelMixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMixLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelMixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMixLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(jPanelMixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jPanelMixOxy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanelMixAir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanelMixGas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(jButtonMix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                );

                javax.swing.GroupLayout jPanelRootLayout = new javax.swing.GroupLayout(jPanelRoot);
                jPanelRoot.setLayout(jPanelRootLayout);
                jPanelRootLayout.setHorizontalGroup(
                        jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelRootLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanelMonitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                                        .addComponent(jPanelMix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                jPanelRootLayout.setVerticalGroup(
                        jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelRootLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelMonitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelMix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelRoot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jFormattedTextFieldFlamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldFlamActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jFormattedTextFieldFlamActionPerformed

        private void jButtonMixMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMixMousePressed
                // TODO add your handling code here:
                jButtonMix.setBackground(Color.magenta);
        }//GEN-LAST:event_jButtonMixMousePressed

        private void jButtonMixMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMixMouseReleased
                // TODO add your handling code here:
                jButtonMix.setBackground(Color.cyan);
        }//GEN-LAST:event_jButtonMixMouseReleased

        private void jButtonMixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMixActionPerformed
                // TODO add your handling code here:
                mairread = (int)(Float.parseFloat(jFormattedTextFieldAir.getText())*100);
                mflamread = (int)(Float.parseFloat(jFormattedTextFieldFlam.getText())*100);
                moxyread = (int)(Float.parseFloat(jFormattedTextFieldOxy.getText())*100);
                ccom = COMMAND_MIX;

        }//GEN-LAST:event_jButtonMixActionPerformed

        private void jFormattedTextFieldAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldAirActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jFormattedTextFieldAirActionPerformed

        private void jFormattedTextFieldOxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldOxyActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jFormattedTextFieldOxyActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FormMixture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FormMixture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FormMixture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FormMixture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FormMixture().setVisible(true);
			}
		});
	}

	//

	private void guidp(){
		redesigngas();
		jLabelMonitorPressure.setText(""+mpressure);
		jLabelMonitorTemp.setText(""+mtemp);
		jLabelMonitorFlammable.setText(""+mflam);
		
		jLabelOxyPress.setText(""+moxypress);
		jLabelAOxyTemp.setText(""+moxytem);
		
		jLabelAirPress.setText(""+mairpress);
		jLabelAAirTemp.setText(""+mairtem);
		
		jLabelAFlamTemp.setText(""+mflamtem);
		jLabelFlamPress.setText(""+mflampress);
	}
	
	private Color getChangeColor(int val,int max){
		int per = 100*(val);
		Color rc = Color.BLACK;
		if(max==0){
			max = 255;
		}
		per = per/max;
		if(per<25){
			rc = Color.cyan;
		}else
		if(per<55){
			rc = Color.GREEN;
		}else
		if(per<75){
			rc = Color.YELLOW;
		}else
		if(per<85){
			rc = Color.ORANGE;
		}else
		if(per<95){
			rc = Color.MAGENTA;
		}else{
			rc = Color.RED;
		}
		
		return rc;
	}
	
	
	public void setmpressure(int mp){
		mpressure=mp;
		jLabelMonitorPressure.setText(mpressure+" bar");
	}
	public void setmtemp(int mp){
		
		mtemp=mp;
		jLabelMonitorTemp.setText(mtemp+" C");
	}
	public void setmflam(int mp){
		
		mflam=mp;
		jLabelMonitorFlammable.setText(mflam+" %");
	}
	public void setmoxy(int mp){
		moxy=mp;
	}
	public void setmmode(int mp){
		mmode=mp;
	}
	public void setmoxytem(int mp){
		moxytem=mp;
		jLabelAOxyTemp.setText(moxytem+" %");
	}
	public void setmoxypress(int mp){
		moxypress=mp;
		jLabelOxyPress.setText(moxypress+" %");
	}
	public void setmflamtem(int mp){
		mflamtem=mp;
		jLabelAFlamTemp.setText(mflamtem+" %");
	}
	public void setmflampress(int mp){
		mflampress=mp;
		jLabelFlamPress.setText(mflampress+" %");
	}
	public void setmairtem(int mp){
		mairtem=mp;
		jLabelAAirTemp.setText(mairtem+" C");
	}
	public void setmflamtype(int mp){
		mflamtype=mp;
	}
	public final int getmoxyread(){
		moxyread=(int)(Float.parseFloat(jFormattedTextFieldOxy.getText())*100);
		return moxyread;
	}
	public final int getmflamread(){
		mflamread=(int)(Float.parseFloat(jFormattedTextFieldFlam.getText())*100);
		return mflamread;
	}
	public final int getmairread(){
		mairread=(int)(Float.parseFloat(jFormattedTextFieldAir.getText())*100);
		return mairread;
	}
	public final void setmflamtypechange(int f){
		 mflamtypechange=f;
	}
	public final int getmflamtype(){
		return mflamtype;
	}
	public final int getccom(){
		return ccom;
	}
	public final void setccom(int mp){
		ccom=mp;
	}
	
	public final void setmixgas(String s){
		mixgasname=s;
	}
	
	public final void redesigngas(){
		if(mflamtypechange>0){
		jPanelMixGas.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, mixgasname, javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial", 3, 12), new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 102, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(0, 51, 153), new java.awt.Color(0, 0, 255)))); // NOI18N
		 jPanelMonitorGas.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, mixgasname, javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial", 3, 12), new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 102, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(0, 51, 153), new java.awt.Color(0, 0, 255)))); // NOI18N
		 jPanelMonitorFlam.setBackground(new java.awt.Color(153, 153, 255));
                jPanelMonitorFlam.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, mixgasname, javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial", 3, 12), new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 102, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(0, 51, 153), new java.awt.Color(0, 0, 255)))); // NOI18N
		mflamtypechange=0;
		}
	}
	private int mpressure=0;
	private int mtemp=0;
	private int mflam=0;
	private int mmode=0;
	private int moxy=0;
	private int moxytem=0;
	private int moxypress=0;
	private int mflamtem=0;
	private int mflampress=0;
	private int mairtem=0;
	private int mairpress=0;
	private int moxyread=0;
	private int mairread=0;
	private int mflamread=0;
	private int mflamtype=0;
	private int ccom=0;
	private int mflamtypechange=0;
	
	private String mixgasname = "propane";
	
	public static final int COMMAND_FIRE = 1010;
	public static final int COMMAND_STOP = 1020;
	public static final int COMMAND_MIX = 1030;
	public static final int COMMAND_ADD = 1040;
	public static final int FIRING = 1110;
	public static final int IDLE = 1120;
	public static final int MODE_IDLE = 1210;
	public static final int MODE_CONNECT = 3;
	public static final int MODE_FIRE = 5;
	public static final int MODE_FIRING = 7;
	public static final int MODE_ALARM = 11;
	public static final int MODE_PREFIRE = 13;
	public static final int MODE_CMD = 19;
	public static final int MODE_TERMINAL = 23;
	public static final int MODE_READ_FIRE = 29;
	public static final int MODE_SAVE_RAW = 31;
	public static final int MODE_SAVING_RAW = 37;
	public static final int MODE_ANALYS_RAW = 41;
	public static final int MODE_ANALYSING_RAW = 43;
	public static final int MODE_SAVE_ANALYS = 47;
	public static final int MODE_SAVING_ANALYS = 53;
	public static final int MODE_GRAPH = 59;
	public static final int MODE_START_JOB = 61;
	public static final int MODE_JOB_DONE = 67;
	public static final int MODE_MONITORING = 71;
	public static final int FLAM_MTHANE = 20102;
	public static final int FLAM_PROPANE = 20102;
	public static final int FLAM_BUTANE = 20102;
	public static final int FLAM_ETHYLENE = 20102;
	public static final int FLAM_HYDROGEN = 20102;
	public static final int DEFLAGRATION = 0;
	public static final int DETONATION = 1;
	public static final String[] FLAM_GAS = {"methane","Hexane","propane","ethylene","Hydrogen"};
	public static final String[] EXPLOTION_TYPE_NAME= {"Deflagration","Detonation","Burning"};
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButtonMix;
        private javax.swing.JFormattedTextField jFormattedTextFieldAir;
        private javax.swing.JFormattedTextField jFormattedTextFieldFlam;
        private javax.swing.JFormattedTextField jFormattedTextFieldOxy;
        private javax.swing.JLabel jLabelAAirTemp;
        private javax.swing.JLabel jLabelAFlamTemp;
        private javax.swing.JLabel jLabelAOxyTemp;
        private javax.swing.JLabel jLabelAirPress;
        private javax.swing.JLabel jLabelFlamPress;
        private javax.swing.JLabel jLabelMonitorFlammable;
        private javax.swing.JLabel jLabelMonitorPressure;
        private javax.swing.JLabel jLabelMonitorTemp;
        private javax.swing.JLabel jLabelOxyPress;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanelAirPres;
        private javax.swing.JPanel jPanelAirTem;
        private javax.swing.JPanel jPanelGasPres;
        private javax.swing.JPanel jPanelGasTem;
        private javax.swing.JPanel jPanelMix;
        private javax.swing.JPanel jPanelMixAir;
        private javax.swing.JPanel jPanelMixGas;
        private javax.swing.JPanel jPanelMixOxy;
        private javax.swing.JPanel jPanelMonitor;
        private javax.swing.JPanel jPanelMonitorAir;
        private javax.swing.JPanel jPanelMonitorFlam;
        private javax.swing.JPanel jPanelMonitorGas;
        private javax.swing.JPanel jPanelMonitorOxy;
        private javax.swing.JPanel jPanelMonitorPressure;
        private javax.swing.JPanel jPanelMonitorTemp;
        private javax.swing.JPanel jPanelOxyPres;
        private javax.swing.JPanel jPanelOxyTem;
        private javax.swing.JPanel jPanelRoot;
        // End of variables declaration//GEN-END:variables
}
