/*
 * Copyright (C) 2024 koalium
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package departed;

import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author koalium
 */
public class Log extends javax.swing.JFrame {

	/**
	 * Creates new form log
	 */
	public Log() {
		initComponents();
		logstring = new StringBuffer();
		timi();
		jTextAreaLogs.setAutoscrolls(true);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLayeredPane4 = new javax.swing.JLayeredPane();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTextAreaLogs = new javax.swing.JTextArea();

                setTitle("Log of Flame Arrester tester");
                setLocation(new java.awt.Point(0, 153));
                setName("frameLog"); // NOI18N
                setPreferredSize(new java.awt.Dimension(500, 550));

                jLayeredPane4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Log:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED))); // NOI18N

                jTextAreaLogs.setColumns(20);
                jTextAreaLogs.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
                jTextAreaLogs.setRows(5);
                jTextAreaLogs.addInputMethodListener(new java.awt.event.InputMethodListener() {
                        public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                        }
                        public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                                jTextAreaLogsInputMethodTextChanged(evt);
                        }
                });
                jScrollPane1.setViewportView(jTextAreaLogs);

                jLayeredPane4.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

                javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
                jLayeredPane4.setLayout(jLayeredPane4Layout);
                jLayeredPane4Layout.setHorizontalGroup(
                        jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jLayeredPane4Layout.setVerticalGroup(
                        jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                                .addContainerGap())
                );

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLayeredPane4)
                                .addContainerGap())
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLayeredPane4)
                                .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jTextAreaLogsInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextAreaLogsInputMethodTextChanged
                // TODO add your handling code here:
                jTextAreaLogs.setAutoscrolls(true);
        }//GEN-LAST:event_jTextAreaLogsInputMethodTextChanged

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Log().setVisible(true);
			}
		});
	}
	
	private  TimerTask tt(){
		
		TimerTask timerTask =  new TimerTask() {
			@Override
			public void run() {
				if(reloggin ){
					jTextAreaLogs.setText(logstring.substring(0));
					
					reloggin=false;
				}
				if(adloggin ){
					jTextAreaLogs.append(appstring);
					adloggin=false;
				}
				

			}
		};
		return timerTask;
	}

	//
	private  void timi(){
		timer = new Timer("monitoring");
		timer.scheduleAtFixedRate(tt(), 50, 50);
	}
	
	public void setlogger(String l,boolean nl){
		if(logstring==null){
			logstring = new StringBuffer();
		}
		if(l!=null){
			logstring.append(l);
			if(nl){
				logstring.append("\n");
			}
			
			reloggin = true;
		}
	}
	public void addlogger(String l,boolean nl){
		
		if(l!=null){
			appstring = l;
			if(nl){
				appstring=appstring+"\n";
			}
			
			logstring.append(appstring);
			adloggin = true;
		}
	}
	
	Timer timer;
	private StringBuffer logstring;
	private static boolean reloggin = false;
	private static boolean adloggin = false;
	private String appstring ="";

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLayeredPane jLayeredPane4;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextArea jTextAreaLogs;
        // End of variables declaration//GEN-END:variables
}
