/*
 * The MIT License
 *
 * Copyright 2025 koalium.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package departed;

import java.awt.Color;

/**
 *
 * @author koalium
 */
public class FormFire extends javax.swing.JFrame {

	/**
	 * Creates new form FormFire
	 */
	public FormFire() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanelRoot = new javax.swing.JPanel();
                jPanelControl = new javax.swing.JPanel();
                jButtonFire = new javax.swing.JButton();
                jButtonStop = new javax.swing.JButton();
                jPanel3 = new javax.swing.JPanel();
                jPasswordFieldFire = new javax.swing.JPasswordField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setLocation(new java.awt.Point(553, 53));
                setName("frameFire"); // NOI18N

                jPanelControl.setBackground(new java.awt.Color(153, 153, 255));
                jPanelControl.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.gray, java.awt.Color.darkGray, java.awt.Color.gray, java.awt.Color.lightGray))); // NOI18N
                jPanelControl.setForeground(new java.awt.Color(204, 204, 255));
                jPanelControl.setAutoscrolls(true);
                jPanelControl.setDoubleBuffered(false);

                jButtonFire.setBackground(new java.awt.Color(102, 255, 51));
                jButtonFire.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jButtonFire.setForeground(java.awt.Color.black);
                jButtonFire.setText("Fire");
                jButtonFire.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                jButtonFireMousePressed(evt);
                        }
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jButtonFireMouseReleased(evt);
                        }
                });
                jButtonFire.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonFireActionPerformed(evt);
                        }
                });

                jButtonStop.setBackground(java.awt.Color.red);
                jButtonStop.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jButtonStop.setForeground(java.awt.Color.black);
                jButtonStop.setText("Stop");
                jButtonStop.setPreferredSize(new java.awt.Dimension(92, 84));
                jButtonStop.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                jButtonStopMousePressed(evt);
                        }
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                jButtonStopMouseReleased(evt);
                        }
                });
                jButtonStop.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonStopActionPerformed(evt);
                        }
                });

                jPanel3.setBackground(new java.awt.Color(153, 153, 255));
                jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "password", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED))))); // NOI18N

                jPasswordFieldFire.setColumns(6);
                jPasswordFieldFire.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jPasswordFieldFire.setText("8");
                jPasswordFieldFire.setToolTipText("");

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPasswordFieldFire, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPasswordFieldFire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jPanelControlLayout = new javax.swing.GroupLayout(jPanelControl);
                jPanelControl.setLayout(jPanelControlLayout);
                jPanelControlLayout.setHorizontalGroup(
                        jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelControlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonFire, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                jPanelControlLayout.setVerticalGroup(
                        jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonFire, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(18, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jPanelRootLayout = new javax.swing.GroupLayout(jPanelRoot);
                jPanelRoot.setLayout(jPanelRootLayout);
                jPanelRootLayout.setHorizontalGroup(
                        jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelControl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                jPanelRootLayout.setVerticalGroup(
                        jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButtonFireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFireActionPerformed
                // TODO add your handling code here:
                if(this.mode!=MODE_FIRING){
                        this.mode=MODE_FIRING;
                        jButtonFire.setBackground(Color.magenta);
                        cpass = jPasswordFieldFire.getPassword().length;
                        this.command=COMMAND_FIRE;
                }
		

        }//GEN-LAST:event_jButtonFireActionPerformed

        private void jButtonStopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStopMousePressed
                // TODO add your handling code here:
                jButtonStop.setBackground(Color.gray);
		this.command=COMMAND_STOP;
        }//GEN-LAST:event_jButtonStopMousePressed

        private void jButtonStopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStopMouseReleased
                // TODO add your handling code here:
                jButtonStop.setBackground(Color.red);
        }//GEN-LAST:event_jButtonStopMouseReleased

        private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
                // TODO add your handling code here:
                command=COMMAND_STOP;

        }//GEN-LAST:event_jButtonStopActionPerformed

        private void jButtonFireMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFireMousePressed
                // TODO add your handling code here:
		if(this.mode!=MODE_FIRING){
                        this.mode=MODE_FIRING;
                        jButtonFire.setBackground(Color.magenta);
                        cpass = jPasswordFieldFire.getPassword().length;
                        command=COMMAND_FIRE;
                }
        }//GEN-LAST:event_jButtonFireMousePressed

        private void jButtonFireMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFireMouseReleased
                // TODO add your handling code here:
        }//GEN-LAST:event_jButtonFireMouseReleased

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FormFire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FormFire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FormFire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FormFire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		/*java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FormFire().setVisible(true);
			}
		});*/
	}

	
	//
	public final int getcpass(){
		return cpass;
	}
	//
	public final int getcommand(){
		return this.command;
	}
	//
	
	public void setcommand(final int cc){
		 command=cc;
	}
	
	public void setframename(final String n){
		setTitle(n);
	}
	public void setcmode(final int cc){
		 mode=cc;
		 if(mode==MODE_IDLE){
			 jButtonFire.setBackground(Color.CYAN);
		 }
	}
	//
	public final int getcmode(){
		return mode;
	}
	//
	public void setfatype(final int cc){
	}
	//
	public void setexplosiontype(final int cc){
	}
	//
	public void setgasmixturesign(final int cc){
	}
	//
	
	private int cpass;
	private int command;
	private int mode = 0;

	
	public static final int COMMAND_FIRE = 1010;
	public static final int COMMAND_STOP = 1020;
	public static final int COMMAND_MIX = 1030;
	public static final int COMMAND_ADD = 1040;

	public static final int MODE_IDLE = 1210;
	public static final int MODE_CONNECT = 3;
	public static final int MODE_FIRE = 5;
	public static final int MODE_FIRING = 7;
	public static final int MODE_ALARM = 11;
	public static final int MODE_PREFIRE = 13;
	public static final int MODE_CMD = 19;
	public static final int MODE_TERMINAL = 23;
	public static final int MODE_READ_FIRE = 29;
	public static final int MODE_SAVE_RAW = 31;
	public static final int MODE_SAVING_RAW = 37;
	public static final int MODE_ANALYS_RAW = 41;
	public static final int MODE_ANALYSING_RAW = 43;
	public static final int MODE_SAVE_ANALYS = 47;
	public static final int MODE_SAVING_ANALYS = 53;
	public static final int MODE_GRAPH = 59;
	public static final int MODE_START_JOB = 61;
	public static final int MODE_JOB_DONE = 67;
	public static final int MODE_MONITORING = 71;
	public static final int FLAM_MTHANE = 20102;
	public static final int FLAM_PROPANE = 20102;
	public static final int FLAM_BUTANE = 20102;
	public static final int FLAM_ETHYLENE = 20102;
	public static final int FLAM_HYDROGEN = 20102;
	public static final int DEFLAGRATION = 0;
	public static final int DETONATION = 1;
	public static final String[] FLAM_GAS = {"methane","Hexane","propane","ethylene","Hydrogen"};
	public static final String[] EXPLOTION_TYPE_NAME= {"Deflagration","Detonation","Burning"};
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButtonFire;
        private javax.swing.JButton jButtonStop;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanelControl;
        private javax.swing.JPanel jPanelRoot;
        private javax.swing.JPasswordField jPasswordFieldFire;
        // End of variables declaration//GEN-END:variables
}
